# Generated by Django 5.1.7 on 2025-04-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('arquivo', models.FileField(upload_to='uploads/excel')),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
