# Generated by Django 5.1.7 on 2025-04-24 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelInterfaceAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aba', models.CharField(max_length=100)),
                ('nome_lista', models.CharField(max_length=100)),
                ('descricao_lista', models.TextField(blank=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('excel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='ExcelInterfaceAPP.excel')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistITEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=255)),
                ('statusItem', models.BooleanField(default=False)),
                ('descricaoItem', models.TextField(blank=True)),
                ('Lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemLista', to='ExcelInterfaceAPP.checklist')),
            ],
        ),
    ]
