# Generated by Django 5.1.7 on 2025-05-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelInterfaceAPP', '0002_checklist_checklistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aba', models.CharField(max_length=100)),
                ('linha_index', models.IntegerField()),
                ('coluna', models.CharField(max_length=100)),
                ('checked', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('aba', 'linha_index', 'coluna')},
            },
        ),
        migrations.CreateModel(
            name='TextStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aba', models.CharField(max_length=100)),
                ('linha_index', models.IntegerField()),
                ('coluna', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('aba', 'linha_index', 'coluna')},
            },
        ),
    ]
